### ISSUE TITLE
Using require instead of import

### ISSUE THREAD

**Issue by mario-lemes** [smikhalevski/react-scroll-box#1]
Hey @smikhalevski,

Great job in this component!

I'm wondering if it's possible use 'require' in order to import the component instead of 'import'. If is that possible, How is suppose to be? 

Thank you.

**Comment by smikhalevski** [comment]
Hello @Yonirt,

Yes, this is surely possible:

`const {ScrollBox, GenericScrollBox, FastTrack, ScrollAxes} = require('react-scroll-box');`

or in ES5 way:

`var ScrollBox = require('react-scroll-box').ScrollBox;`

I'll add this to the docs.
