### ISSUE TITLE
How to set up the easing function?

### ISSUE THREAD

**Issue by mario-lemes** [smikhalevski/react-scroll-box#3]
Hey @smikhalevski,

Sorry for bother you, I'm trying to set up a custom easing function like this: 

```
scrollBoxProps: {   
                axes: ScrollAxes.Y,
                disabled: false,
                captureKeyboard: true,
                hoverProximity: 50,
                fastTrackDuration: 500,
                fastTrack: FastTrack.REWIND,            
                outset: false,      
                easing: this.easeOutQuad,
                style: {height: window.innerHeight - h},
            },
    easeOutQuad: function(x, t, b, c, d){
        return -c *(t/=d)*(t-2) + b; 
    },
```

But it seem dosn't work, is there any specific way to do it?

Thanks again for your help.

UPDATED: Sorry, but it works perfectly, but just when you click on scroll track. There is any way to make smooth scrolling?

**Comment by smikhalevski** [comment]
Hello, @Yonirt 

Update with smooth scrolling will be available in a couple of hours:) I'm working on it right now.

**Comment by smikhalevski** [comment]
@Yonirt, update to `react-scroll-box@0.1.1` and use `scrollDuration` prop for smooth scrolling. Please notice that in this update has some breaking changes (ex. I renamed `FastTrack.REWIND` to `FastTrack.GOTO`).

**Comment by mario-lemes** [comment]
Great work!
